name: Daily Penguin Prediction

on:
  schedule:
    # Run daily at 7:30 AM UTC
    - cron: '30 7 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas scikit-learn seaborn matplotlib xgboost
          
      - name: Run prediction script
        run: python scripts/prediction_api.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/predictions/* index.html
          git commit -m "Update prediction for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push