name: Daily Penguin Prediction
on:
  schedule:
    # Run at 7:30 AM UTC every day
    # - cron: '30 7 * * *'
    - cron: '20 18 * * *'

  # Allow manual triggering
  workflow_dispatch:

# This is the critical part - setting proper permissions
permissions:
  contents: write  # Explicit permission to write to repository contents

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch complete history for better merging
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run prediction
      run: |
        python scripts/prediction-api-script.py
    
    - name: Commit and push results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Copy files to root for GitHub Pages
        cp data/predictions/index.html ./index.html || true
        cp data/predictions/latest_visualization.png ./latest_visualization.png || true
        cp data/predictions/latest.json ./latest.json || true
        cp data/predictions/history.json ./history.json || true
        
        # Stage all changes first before attempting any pull
        git add -A
        
        # Fetch and merge strategy (alternative to pull --rebase)
        git fetch origin main
        git merge --no-edit -X theirs origin/main || true
        
        # Commit any changes
        if [[ -n "$(git status --porcelain)" ]]; then
          git commit -m "Update daily penguin prediction for $(date +'%Y-%m-%d')"
          git push -f
        else
          echo "No changes to commit"
        fi
